config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  devise_for :users
  root 'visitors#index'
  resources :visitors , :posts
  get "bootstrap", to: "visitors#bootstrap"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :visitor
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :visitors
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    belongs_to :user
    has_many :posts , dependent: :destroy

    validates :FullName, presence: true , length: { minimum: 6, too_short: "must have at least %{count} words" }
    validates :Phone_no, presence: true 
   
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @msg1= 'Talent Support Site'
    
  end

  def about
    @msg2 = 'About us'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @visitor = Visitor.find(params[:visitor_id])
        @post = Post.new
      end

    def create 
        puts params
        visitor = Visitor.find(params[:post][:visitor_id])
        Post.create(params.require(:post).permit(:TalentName, :TalentDescription, :visitor_id))
        redirect_to visitor
     end

     def destroy
        Post.find(params[:id]).destroy
        redirect_to visitors_path
    end 


end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    before_action :authenticate_user!, only: [:new , :show]  
    before_action :find_visitor, except: [:index, :new, :create]
   


    def show
        @posts = @visitor.posts
        if @visitor != current_user
        elsif @visitor = current_user
          redirect_to visitors_path
        end
    end
    

    def index
        if @visitors = current_user
        @visitors = current_user.visitors.all
        else 
            redirect_to  user_session_path
        end

    end 

    def new 
        @visitor = Visitor.new
    end

    def create 
        @visitor = Visitor.new(person_params)
       @visitor.user = current_user

        if @visitor.save
            redirect_to "/visitors/#{params[:visitor_id]}/"
            flash[:notice] = 'Well done! You added Information successfully'

          else
            flash[:alert] = 'Oh snap! Try again'
            render 'new'
          end
    end

    def edit
        @visitor = Visitor.find(params[:id])
    end 

    def update
        visitor = Visitor.find(params[:id])
        visitor.update(person_params)
        flash[:notice] = 'Your update successfully'
        redirect_to "/visitors/#{params[:visitor_id]}/"
    end 

    def destroy
        Visitor.find(params[:id]).destroy
        flash[:notice] = 'Pip-Pip!'
        redirect_to   visitors_path
    end 

    private
    def person_params
      params.require(:visitor).permit(:FullName, :Phone_no, :BirthDay)
    end
    def find_visitor
        @visitor = Visitor.find(params[:id])
      end


  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg ">
  <a class="navbar-brand" href="#">Talent Support Site</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/pages/home">Home <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="/pages/about">About Us</a>
      </li>
      <li class="nav-item">
                <a class="nav-link " href="/visitors">My Information</a>
</li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %> 
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'dropdown-item'  %> 
    <%= link_to "Login", new_user_session_path, :class => 'dropdown-item'  %>
        </div>
      </li>
    </ul>
        <% if user_signed_in? %><p> 
  Logged in as &nbsp;<strong><%= current_user.email %></strong>
</p>      
<% end %>
  </div>
  
   <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-4" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TalentsSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>

<link href='https://fonts.googleapis.com/css?family=Montserrat:700' rel='stylesheet' type='text/css'>
  </head>

 
 <body>


<a class="square" href="#">
    <div class="burgerwrap">
        <span></span>
        <span></span>
        <span></span>
    </div>


   <%= render 'layouts/nav' %>


  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @msg2 %></h1>
<pre>This website allow to you to post your talent,
 and the support companies will contact with you to take course or hire you .</pre>

app/views/pages/home.html.erb
<h1>welcome to <strong><%= @msg1 %></strong></h1>
<pre>To add your talent you shoud ,
first got to My information page to 
add you information to allow you to add post about your talent. </pre>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.hidden_field :visitor_id, :value => @visitor.id %>
   <div class="form-group">
  <h2>	<%= f.label :TalentName, 'Choose your Talent Name :', class: "col-md control-label" %></h2>
     <div class="col-md">
    <%= f.select :TalentName , 
    [["Art"], ["Music"],["Photography"],["Drawing"],["Graphics"],["Singing"],["Video Creation"],["Computers / IT"],["Software"],["Typing"]],
     { label: "Choose your Talent :" }, { class: "selectpicker" } %>
       </div>
      </div>

<div class="form-group ">
  <h2>	<%= f.label :TalentDescription, 'Talent Description :', class: "col-md-4 control-label "  %></h2>
    <div class="col-md ">
  	<%= f.text_area :TalentDescription, class: "form-control "  %>
   </div>
      </div>
  <%= f.submit "Submit", :class => "buttonAll" %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post for "<%= @visitor.FullName%>"</h1>


<%= render 'posts/form' %>

app/views/visitors/_form.html.erb
<h1>please , Write Your Information </h1>
<section id="cover">
    <div id="cover-caption">
        <div id="container" class="container">
            <div class="row">
                <div class="col-sm-10 offset-sm-1 text-center">
<%= form_for @visitor , local: true do |f| %>
  <div class="form-group">
  <h2>	<%= f.label :FullName, 'Full Name :' %></h2>
  	<%= f.text_field :FullName , class: "form-control"%>
  </div>
      <div class="form-group">
  <h2>	<%= f.label :Phone_no, 'phone number :' %></h2>
  	<%= f.text_field :Phone_no, class: "form-control" %>
   </div>
      <div class="form-group">
  <h2>	<%= f.label :BirthDay, 'Birth Day :'  %></h2>
  	<%= f.date_select :BirthDay , :start_year=>1990 , :end_year=>2005 ,class: "form-control" %>
  </div>
<br><br>
  <%= f.submit "Submit", :class => "buttonAll" %>
<% end %>
            </div>
        </div>
    </div>
</section>

app/views/visitors/edit.html.erb
<h1> Edit <%= @visitor.FullName%> </h1>

<%= render 'form'%>

app/views/visitors/index.html.erb
<h1> All The Talents </h1>



<%= link_to "My Information ", new_visitor_path, { :class => "boton"}%>


<div class="d-flex justify-content-center">
<% @visitors.each do |visitor|%>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><p>Your Name :</p><%= visitor.FullName%></h5>
    <h5 class="card-subtitle mb-2 text-muted"><p>Your Phone Number :</p><%= visitor.Phone_no%></h5>
    <h5 class="card-text"><p>Your BirthDay :</p><%= visitor.BirthDay%></h5>
    <div class="btn-group" role="group" aria-label="Basic example">
    <a  class="buttonAll"  role="button" aria-pressed="true" href="<%= edit_visitor_path(visitor) %>" >Edit User</a>
    <a class="buttonAll" role="button" aria-pressed="true" data-confirm="Are you sure you want to delete <%= visitor.FullName %>?" data-method="delete" href="/visitors/<%= visitor.id %>" rel="nofollow">Delete User</a>
    <a  class="buttonAll"  role="button" aria-pressed="true" href="<%=  visitor_path(visitor)%>" >See Post</a>

    
  </div>
  </div>
</div>
  <% end %>
  </div>

app/views/visitors/new.html.erb
<% if @visitor.errors.any? %>
  <h3>We've got problems!</h3>
  <h4>
  <%= pluralize(@visitor.errors.count, 'error') %>
  stopped us from saving :
</h4>

<ul>
  <% @visitor.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<% end %>

<%= render partial: 'form' , locals: { visitor: @visitor }%>

app/views/visitors/show.html.erb
<h1> <strong><%= @visitor.FullName %></strong> Posts</h1>
<br><br>

<h3><%= link_to "New Post", new_post_path(:visitor_id => @visitor.id), { :class => "buttonAll"}%></h3>
<br><br>

<div class="d-flex justify-content-center">
<% @posts.each do |post|%>
<div class="card-group">
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <p class="card-title">Talent Name :</p>
<h5 class="card-subtitle mb-2 text-muted"><%= post.TalentName %></h5>
        <p class="card-text">Talent Description :</p>
       <h5 class="card-subtitle mb-2 text-muted"> <%= post.TalentDescription %></h5>
         <div class="btn-group" role="group" aria-label="Basic example">
        <a class="buttonAll" role="button" aria-pressed="true" data-confirm="Are you sure you want to delete <%= post.TalentName %>?" data-method="delete" href="/posts/<%= post.id %>" rel="nofollow"><i class="large material-icons">Delete </i>
   </a>
 </div>
  </div>
  </div>
<% end %>
</div>